import Hls from 'hls.js';
import { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useRef } from 'react';
import styled from 'styled-components';

const Main = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
`;

const url = 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8';

export const Home: NextPage = () => {
  const audioRef = useRef<HTMLAudioElement>(null);
  useEffect(() => {
    if (Hls.isSupported()) {
      const hls = new Hls();
      hls.loadSource(url);
      hls.attachMedia(audioRef.current!);
    }
  }, []);

  const play = () => {
    audioRef.current?.play();
  };

  const pause = () => {
    audioRef.current?.pause();
  };
  return (
    <>
      <Head>
        <title>Next.js and Socket.io Sandbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <meta name="twitter:card" content="player" />
        <meta name="twitter:text:title" content="Twitter Cardで" />
        <meta name="twitter:description" content="HLS動画を表示させる" />
        <meta name="twitter:image" content="https://www.google.co.jp/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" />
        <meta name="twitter:player" content="https://s3-ap-northeast-1.amazonaws.com/xxxxxx/hls.html" />
        <meta name="twitter:player:width" content="640" />
        <meta name="twitter:player:height" content="360" />
        <meta name="twitter:player:stream" content="https://s3-ap-northeast-1.amazonaws.com/xxxxxx/hls.m3u8" />
        <meta name="twitter:player:stream:content_type" content="application/vnd.apple.mpegurl" />
      </Head>
      <Main>
        {/* eslint-disable-next-line jsx-a11y/media-has-caption */}
        <audio ref={audioRef} autoPlay={false} src={url} />
        <button type="button" onClick={play}>play</button>
        <br />
        <button type="button" onClick={pause}>pause</button>
      </Main>
    </>
  );
};

export default Home;
