import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { signIn, signOut, useSession } from 'next-auth/client';
import styled from 'styled-components';

const Main = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
`;

export const Home: NextPage = () => {
  const [session] = useSession();
  return (
    <>
      <Head>
        <title>Next.js and Socket.io Sandbox</title>
        <meta httpEquiv="Content-Security-Policy" content="default-src data: gap://* file://* https://ssl.gstatic.com *; img-src 'self' * data:; style-src 'self' 'unsafe-inline' *; script-src 'self' 'unsafe-eval' 'unsafe-inline' *; connect-src 'self' * ws://* wss://*;" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        {session ? (
          <div>
            {session.user!.email ?? session.user!.name}
            <button type="button" onClick={() => signOut()}>Sign out</button>
          </div>
        ) : (
          <div>
            <button type="button" onClick={() => signIn()}>Sign in</button>
          </div>

        )}
        <Link href="/othello">オセロ</Link>
        <Link href="/uno">UNO(ざっくりやって嫌になった、db欲しい)</Link>
        <Link href="/2048">2048</Link>
      </Main>
    </>
  );
};

export default Home;
