import { NextPage } from 'next';
import Head from 'next/head';
import { io } from 'socket.io-client';
import { useEffect } from 'react';

export const Uno: NextPage = () => {
  useEffect(() => {}, []);
  useEffect(() => {
    const socket = io('/uno', {
      path: '/api/socket',
    });

    socket.on('othello', (othello) => {
      // eslint-disable-next-line no-console
      console.log('othello!!!!!!', othello);
    });
  });

  return (
    <>
      <Head>
        <title>UNO</title>
        <meta httpEquiv="Content-Security-Policy" content="default-src data: gap://* file://* https://ssl.gstatic.com *; img-src 'self' * data:; style-src 'self' 'unsafe-inline' *; script-src 'self' 'unsafe-eval' 'unsafe-inline' *; connect-src 'self' * ws://* wss://*;" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main />
    </>
  );
};

export default Uno;
